language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE magento;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

install:
  - wget -O mage-install.sh http://sys.sonassi.com/mage-install.sh
  - chmod +x mage-install.sh
  - bash mage-install.sh -f -r 1.9.1.0 -l 127.0.0.1 -u root -p root -n magento -s -w http://127.0.0.1 -e admin@admin.com

before_script:
  - mkdir -p build/logs
  - composer require phpunit/phpunit:4.8
  - composer require satooshi/php-coveralls:* --dev

script:
  - vendor/bin/phpunit -c phpunit.xml

after_success:
  - travis_retry php vendor/bin/coveralls
