version: '2'

services:
    php:
        image: pagarme/php:5.4
        volumes:
            - .:/code
        working_dir: /code

    composer:
        image: pagarme/composer
        volumes:
            - .:/code
        working_dir: /code

    mysql:
        image: mysql:5.6
        env_file: .env
        volumes:
            - database:/var/lib/mysql

    magento:
        image: ricardotulio/magento:${MAGENTO_VERSION}
        env_file: .env
        volumes:
            - .:/docker-magento-modules/pagarme/
        working_dir: /var/www
        ports:
            - "8080:80"
        depends_on:
            - mysql

volumes:
    config:
        driver: local
    database:
        driver: local

